{application,gateway,
             [{applications,[kernel,stdlib,elixir,logger,hackney,cowboy,plug]},
              {description,"Multi port HTTP Proxy and support record/play request."},
              {modules,['Elixir.Gateway','Elixir.Gateway.Agent',
                        'Elixir.Gateway.Data','Elixir.Gateway.Format',
                        'Elixir.Gateway.Handle','Elixir.Gateway.Play.Body',
                        'Elixir.Gateway.Play.Data',
                        'Elixir.Gateway.Play.Paths',
                        'Elixir.Gateway.Play.Response',
                        'Elixir.Gateway.Policies',
                        'Elixir.Gateway.Record.Response',
                        'Elixir.Gateway.Supervisor','Elixir.Gateway.Utils',
                        'Elixir.Gateway.Utils.File']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]},
              {mod,{'Elixir.Gateway',[]}}]}.
